language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - mysql -e 'create database `symfony`;'
  - composer install

before_script:
  - php app/console doctrine:schema:update --force
  - composer self-update

script:
  - phpunit -c app
