fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    prefix:   /{_locale}
    type:     annotation
    requirements:
        # The first "|" makes the locale optional
        _locale: "|de|en"

optional_locale:
    resource: "@OptionalLocaleBundle/Resources/config/routing.yml"
    prefix:   /

# Removes trailing slash on request
remove_tailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Usability:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
